service: simplefood-api

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev
  tags:
    project: SimpleFood

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  get_products:
    handler: functions/get_products.handler
    events:
      - http:
          path: /get-products
          method: post
          cors: true
      - http:
          path: /get-products
          method: get
          cors: true
  get_orders:
    handler: functions/get_orders.handler
    events:
      - http:
          path: /get-orders
          method: post
          cors: true
  add_product:
    handler: functions/add_product.handler
    events:
      - http:
          path: /add-product
          method: post
          cors: true
  delete_product:
    handler: functions/delete_product.handler
    events:
      - http:
          path: /delete-product
          method: post
          cors: true
  add_order:
    handler: functions/add_order.handler
    events:
      - http:
          path: /add-order
          method: post
          cors: true
