service: takeaway-api

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev
  tags:
    project: takeaway

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  get_products:
    handler: functions/get_products.handler
    events:
      - http:
          path: /get_products
          method: post
          cors: true
      - http:
          path: /get_products
          method: get
          cors: true
